### ISSUE TITLE
Change repo name to "wptrt-customize-section-button"?

### ISSUE THREAD

**Issue by justintadlock** [WPTRT/customize-section-button#2]
Essentially, all this repo does is create a "Button Section".  It doesn't technically have to be a "pro" or "upsell" link.  The button text and link can literally be anything.  Changing it would make it more generic and useful for a wider variety of projects.

Thoughts?

**Comment by dingo-d** [comment]
Yeah, since `composer` doesn't have the packages ability like `npm` has we cannot have `@wptrt-snippets/customize-section-button` package for example (sadly). So I think this will have to be changed.

But I don't think that the `wptrt-` prefix is needed since this is already in the `WPTRT` repo, so if installing with customizer this is going to be `composer require wptrt/customizer-upsell-button` (the name of the package here is just an example, it can be named better).

**Comment by justintadlock** [comment]
I'm so used to working under my own GitHub account and prefixing per-project.  I wasn't thinking at all about not needing the `wptrt-` prefix. 🤦‍♂ That makes total sense.

---

On the subject of naming, several people have asked about a "customizer framework" as part of this larger project.  While I'm not interested in a framework, per say, we should think about the bigger picture with naming.

With that in mind, I'm thinking all customizer-related repos be named using the `customize-{$type}-{$name}` method.

- `customize-section-{$name}`
- `customize-control-{$name}`
- `customize-setting-{$name}`

This would provide some consistency.  Eventually, if we ever do have enough sections, controls, and settings to create a "framework," it'd be easy to create a simple repo and have all of those as a dependency.  Theme devs could theoretically do it on their own too.

Just thinking here.  I'd like to nail some of these details down before going further.

**Comment by DannyCooper** [comment]
`customize-section-button` makes a lot of sense to me. +1
